name: Codecov Report

on:
  push:
    branches:
      - main # O workflow ser치 executado apenas quando houver um commit ou merge na branch `main`

jobs:
  Codecov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Garantir que o reposit칩rio seja clonado completamente

      - name: Install pre-requisites
        run: sudo apt-get update && sudo apt-get install libsqlite3-dev

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin # Instala o cargo-tarpaulin para gerar o relat칩rio de cobertura

      - name: Run tests with coverage
        run: export RUST_TEST_THREADS=1 && cargo tarpaulin --out lcov # Executa os testes e gera o relat칩rio no formato html

      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true # optional (default = false)
          files: ./lcov.info # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          verbose: true # optional (default = false)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
